# Doctrine-Konfiguration wird im Hauptprojekt definiert
# Diese Datei dient nur als Template/Beispiel für die Integration

# Inhalt von config/packages/doctrine.yaml (bitte ggf. anpassen, falls Bundle-spezifisch) 

# CompanyOS Core Bundle Doctrine Configuration

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            uuid: CompanyOS\Infrastructure\Persistence\Doctrine\UuidType
            email: CompanyOS\Infrastructure\Persistence\Doctrine\EmailType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            CompanyOSCore:
                type: attribute
                is_bundle: true
                dir: '%kernel.project_dir%/vendor/companyos/core/src/Domain'
                prefix: 'CompanyOS\Domain'
                alias: CompanyOS
        controller_resolver:
            auto_mapping: false
    migrations:
        paths:
            'CompanyOS\Migrations':
                - '%kernel.project_dir%/vendor/companyos/core/src/Migrations'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system 