# Doctrine-Konfiguration wird im Hauptprojekt definiert
# Diese Datei dient nur als Template/Beispiel für die Integration

# Inhalt von config/packages/doctrine.yaml (bitte ggf. anpassen, falls Bundle-spezifisch) 

# CompanyOS Core Bundle Doctrine Configuration
# Diese Konfiguration wird automatisch vom Bundle geladen

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            uuid: CompanyOS\Bundle\CoreBundle\Infrastructure\Persistence\Doctrine\UuidType
            email: CompanyOS\Bundle\CoreBundle\Infrastructure\Persistence\Doctrine\EmailType
    orm:
        mappings:
            CompanyOSCore:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain'
                alias: CompanyOS
            CompanyOSUser:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/User/Domain/Entity'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\User\Domain\Entity'
                alias: CompanyOSUser
            CompanyOSAuth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/Auth/Domain/Entity'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\Auth\Domain\Entity'
                alias: CompanyOSAuth
            CompanyOSRole:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/Role/Domain/Entity'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\Role\Domain\Entity'
                alias: CompanyOSRole
            CompanyOSPlugin:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/Plugin/Domain/Entity'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\Plugin\Domain\Entity'
                alias: CompanyOSPlugin
            CompanyOSWebhook:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/Webhook/Domain/Entity'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\Webhook\Domain\Entity'
                alias: CompanyOSWebhook
            CompanyOSSettings:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/Settings/Domain/Entity'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\Settings\Domain\Entity'
                alias: CompanyOSSettings
            CompanyOSEvent:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/src/Domain/Event'
                prefix: 'CompanyOS\Bundle\CoreBundle\Domain\Event'
                alias: CompanyOSEvent
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
    migrations:
        paths:
            'CompanyOS\Bundle\CoreBundle\Migrations':
                - '%kernel.project_dir%/vendor/companyos/core/src/Migrations'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system 