# Inhalt von config/packages/league_oauth2_server.yaml (bitte ggf. anpassen, falls Bundle-spezifisch) 

league_oauth2_server:
    authorization_server:
        private_key: '%kernel.project_dir%/var/oauth/private.key'
        encryption_key: '%env(OAUTH2_ENCRYPTION_KEY)%'
        enable_client_credentials_grant: true
        enable_password_grant: true
        enable_refresh_token_grant: true
        access_token_ttl: 'PT1H'
        refresh_token_ttl: 'P1M'
    resource_server:
        public_key: '%kernel.project_dir%/var/oauth/public.key'
    persistence:
        doctrine:
            entity_manager: default
    scopes:
        available: ['basic']
        default: ['basic']

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null 