# CompanyOS Core Bundle Security Configuration
# Diese Konfiguration wird automatisch von der Haupt-Anwendung geladen

security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        CompanyOS\Bundle\CoreBundle\Domain\User\Domain\Entity\User:
            algorithm: auto
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        companyos_user_provider:
            id: CompanyOS\Bundle\CoreBundle\Infrastructure\User\Security\UserProvider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            oauth2: ~
        main:
            pattern: ^/
            stateless: false
    
    # Access Control für CoreBundle API-Endpunkte
    access_control:
        # Öffentliche API-Dokumentation
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc\.json$, roles: PUBLIC_ACCESS }
        
        # Öffentliche OAuth2 und Auth-Endpunkte
        - { path: ^/api/oauth2/token, roles: PUBLIC_ACCESS }
        - { path: ^/api/oauth2/authorize, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        
        # Öffentliche System-Endpunkte
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/version, roles: PUBLIC_ACCESS }
        
        # Alle anderen API-Endpunkte erfordern Authentifizierung
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon 