# CompanyOS Core Bundle Validator Configuration

framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        auto_mapping:
            CompanyOS\Core\: []
        mapping:
            paths:
                - '%kernel.project_dir%/vendor/companyos/core/src/Domain'
            namespaces:
                CompanyOS\Bundle\CoreBundle\: []

when@test:
    framework:
        validation:
            not_compromised_password: false 