version: 2
updates:
  # Composer Dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dbechstein"
    assignees:
      - "dbechstein"
    commit-message:
      prefix: "composer"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    ignore:
      # Ignoriere Pre-Release Versionen
      - dependency-name: "*"
        versions: ["*-alpha*", "*-beta*", "*-rc*", "*-dev*"]
    # Gruppiere Updates für bessere Übersicht
    groups:
      symfony:
        patterns:
          - "symfony/*"
        update-types:
          - "minor"
          - "patch"
      doctrine:
        patterns:
          - "doctrine/*"
        update-types:
          - "minor"
          - "patch"
      phpunit:
        patterns:
          - "phpunit/*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dbechstein"
    assignees:
      - "dbechstein"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions" 