doctrine:
    orm:
        mappings:
            CompanyOSCoreBundle:
                is_bundle: true
                type: attribute
                dir: '%kernel.project_dir%/CompanyOSCoreBundle/Domain'
                prefix: 'CompanyOS\Domain'
                alias: CompanyOS
    migrations:
        paths:
            'CompanyOS\Core\Bundle':
                - '%kernel.project_dir%/CompanyOSCoreBundle/Resources/migrations' 