# Inhalt von config/routes.yaml (bitte ggf. anpassen, falls Bundle-spezifisch) 

# CompanyOS Core Bundle Routes
companyos_core:
    resource: '@CompanyOSCoreBundle/Application/'
    type: annotation
    prefix: /api

# User API
user_api:
    resource: '../../User/Application/Controller/'
    type: attribute
    prefix: /api/users

# Role API
role_api:
    resource: '../../Role/Application/Controller/'
    type: attribute
    prefix: /api/roles

# Plugin API
plugin_api:
    resource: '../../Plugin/Application/Controller/'
    type: attribute
    prefix: /api/plugins

# Webhook API
webhook_api:
    resource: '../../Webhook/Application/Controller/'
    type: attribute
    prefix: /api/webhooks

# Settings API
settings_api:
    resource: '../../Settings/Application/Controller/'
    type: attribute
    prefix: /api/settings

# Auth API
auth_api:
    resource: '../../Auth/Application/Controller/'
    type: attribute
    prefix: /api/oauth2 