# CompanyOS Core Bundle Routes
# Diese Datei sollte im Hauptprojekt in config/routes.yaml importiert werden:
# company_os_core:
#     resource: '@CompanyOSCoreBundle/Resources/config/routes.yaml'

# User Routes
user_routes:
    resource: '@CompanyOSCoreBundle/Resources/config/routes/user.yaml'
    type: attribute
    prefix: /api/users

# Role Routes
role_routes:
    resource: '@CompanyOSCoreBundle/Resources/config/routes/role.yaml'
    type: attribute
    prefix: /api/roles

# Plugin Routes
plugin_routes:
    resource: '@CompanyOSCoreBundle/Resources/config/routes/plugin.yaml'
    type: attribute
    prefix: /api/plugins

# System Routes
system_routes:
    resource: '@CompanyOSCoreBundle/Resources/config/routes/system.yaml'
    type: attribute
    prefix: /api/system

# Webhook Routes
webhook_routes:
    resource: '@CompanyOSCoreBundle/Resources/config/routes/webhook.yaml'
    type: attribute
    prefix: /api/webhooks

# Settings Routes
settings_routes:
    resource: '@CompanyOSCoreBundle/Resources/config/routes/settings.yaml'
    type: attribute
    prefix: /api/settings 