# CompanyOS Core Bundle Security Configuration
# Diese Konfiguration kann im Hauptprojekt überschrieben werden

security:
    providers:
        companyos_user_provider:
            entity:
                class: CompanyOS\Bundle\CoreBundle\Domain\User\Domain\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            oauth2: ~

    access_control:
        # Öffentliche Endpunkte
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/token, roles: PUBLIC_ACCESS }
        - { path: ^/authorize, roles: PUBLIC_ACCESS }
        # Geschützte API-Endpunkte
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY } 