services:
    _defaults:
        autowire: true
        autoconfigure: true

    CompanyOS\Core\Settings\:
        resource: '../../'
        exclude:
            - '../../Domain/Entity/'
            - '../../Infrastructure/Resources/'

    # Repository
    CompanyOS\Core\Settings\Infrastructure\Persistence\DoctrineCompanySettingsRepository:
        tags:
            - { name: 'doctrine.orm.entity_listener' }

    # Services
    CompanyOS\Core\Settings\Application\Service\SettingsService:
        public: true
        arguments:
            $queryBus: '@messenger.default_bus'

    # Controllers
    CompanyOS\Core\Settings\Application\Controller\SettingsController:
        public: true
        arguments:
            $commandBus: '@messenger.default_bus'
            $queryBus: '@messenger.default_bus'
            $validator: '@validator'

    # Event Subscribers
    CompanyOS\Core\Settings\Infrastructure\EventSubscriber\SettingsEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' } 